# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e91fe49283f31fb64882e4c5353e0230fe5d03a36548985ca199761797ebc020a2e592153adbe4191987ab8114a4903172f630041c89a18e2e8115db99184eb

test:
  secret_key_base: e50e20df316cd40ac7d1d8794c792ef3a9aa669ebcfb8b4374a01ef84d7de488d877187bfb4d45f8d2c8e95a127bd0adbeaa7ac4fbcc7d64ed2fbb7b4451860a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
